# Generated by Django 5.1.1 on 2024-10-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("like_count", models.IntegerField()),
                ("link", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField()),
            ],
        ),
    ]
