# Generated by Django 5.1.1 on 2024-10-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_date_updated_alter_blog_date_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
